SchrodingersGat/KiBoM

KiBOM_CLI.py, README.md
I think a Quick Start is needed because many users won't want to use all the features, they just want to test it.  Almost an Installation section since  the installation might be a little different for various platforms (I am on Ubuntu, the BOM dialog opened a file chooser on /usr/bin, which I didn't expect, but I found that I could navigate to wherever I had unzipped.  Maybe the next version of KiCad will default to a standard location for plugins, or maybe Ubuntu messed it up.)
Also, you might want a little more context for users.  My use case is I want to order from Digikey.  (And I quickly learned that KiBOM did exactly the right thing.)  Another use case is to pull from your own inventory.  Another use case might just be a list for assembly instructions.
Of course, edit or reject as …
=> Add a Quick Start section to README.md

KiBOM/component.py
If a footprint isn't defined, then the call to to split() will return an array with only one element.
Calling `getFootprint().split(":")[1]` will generate an array out of bounds exception.
Resolve this by only returning a footprint value if the footprint contains a `:` as expected.
=> component: Check if footprint has expected len

KiBOM/component.py
This pull request prioritizes the `Description` and `Datasheet` field of a component over the value defined in the library.
I use this because often times a part like a "Resistor" has a useless datasheet and description in the library.  Instead I can link to the actual datasheet to the component and a useful description such as `RES SMD 10K 1% 0201 1/16W`.
Thanks!
=> Prioritize component fields over library fields

.gitignore, KiBOM/csv_writer.py, KiBOM/preferences.py, KiBOM_CLI.py, README.md
Added -s and --separator options to override the CSV separator (delimiter) with respect to auto detection when nothing specified.
This allow to use `;` delimiter to read the BOM with Excel without replacing the commas. 
It's a quick feature, i would added it to the configuration file, but it looks a bit complicated to me (and i don't have a ton of time)
However, if you think that the feature should appear in the conf file, i can try to look into it...
The script is quite useful btw, nice work 😄 
Best,
Julien
=> Added CSV separator override option

KiBOM/component.py
README.md says:
"If the fit_field begins with a '+' character, if will ONLY be included in the matching configuration."
so make +foo implement that; it seems to have bitrotted or to never have
been implemented/tested.
=> Fix PCB configurations feature for "+blah"

KiBOM_CLI.py, README.md
=> Use "variant" instead of "revision"

.travis.yml, KiBOM_CLI.py, README.md, tests/common.bash, tests/sanity.bash
- Just runs a --help on each version of Python
- 2.7, 3.3, 3.4, 3.5, 3.6
- 3.7-dev, and nightly (which are allowed to fail)
This should make sure changes keep being compatible.
Will need PR #30 in order to pass the tests (Python 2.7 does pass though): https://travis-ci.org/haata/KiBoM/builds/378204678 vs. https://travis-ci.org/haata/KiBoM/builds/378203999
The README.md link will have to change once Travis-CI is setup on your end.
=> Adding basic support for Travis-CI testing

bomlib/component.py
I am suggesting this small modification for fixing an error that happens when you generate the BOM with missing footprints.
=> small fix for missing footprint

bomlib/component.py
Consider a `Config` field for a component is `-bat_pwr,+ext_pwr,+dual_pwr,+kitchen_sink`
Let's ignore the exclude (bat_pwr). This component is present in multiple variants; ext_pwr, dual_pwr, kitchen_sink
Given the current code below, and assuming we selected ext_pwr:
```python
result = True
for opt in opts:
#options that start with '-' are explicitly removed from certain configurations
if opt.startswith('-') and opt[1:].lower() == self.prefs.pcbConfig.lower():
result = False
break
if opt.startswith("+"):
result = False
if opt[1:].lower() == self.prefs.pcbConfig.lower():
result = True
```
This means that the result will be `False` for this component because it loops through opts multiple times.  The _last_ opt is +kitchen_sink, but since it sets result to `False`, and the following `if` …
=> Fix for how config works

KiBOM_CLI.py, bomlib/preferences.py
Bom.ini values are used if the command line arguments are *not* provided.
This allows project defaults to be set as generally the `pcbConfig` options will be project specific, but KiCAD persists the command line options between projects requiring manual entry of these each time you switch project.
This is also helpful for projects where version control is used as the variant and number will persist in `bom.ini` if it is in git/whatever vcs.
=> Add optional `bom.ini` configuration of `boards` (qty of PCBs in the BOM) and `pcbConfig` (the PCB variant).

bomlib/html_writer.py
The KiCad symbol libraries use `~` to denote certain fields as "empty" eg. when there is no datasheet. Not sure why exactly, I guess something breaks when it is *actually* empty. I think KiBoM should give these a red background.
=> Display "~" as empty fields

bomlib/component.py
=> Fix group_connectors option not working

KiBOM_CLI.py, README.md, bomlib/bom_writer.py, bomlib/preferences.py, bomlib/xlsx_writer.py
Optional XLSX output format support. Automatically detects XlsxWriter module.
=> Feature xlsx

KiBOM_CLI.py, README.md, bomlib/preferences.py
Hi @SchrodingersGat,
Just following up from yesterdays pull you did for #37 which added support for multiple variants. I had seen the value in adding these variants names to the BoM filename, and @AngusP (author of #37) had intended himself to add support for this. I believe this patch I have written satisfies this feature. 
There is a certain amount of personal preference when it comes to how this variant name actually gets included in the filename so in particular I would advise that you review line 183 of `KiBOM_CLI.py` (and therefore line 210 of `README.md`).
Cheers.
Changes to `KiBOM_CLI.py`:
- Add logic to include variant name in filename if flag is set.
- Clean up some rogue whitespace.
Changes to `README.md`:
- Add description for new `includeVariantName` flag.
- Add …
=> Add flag to output variant name to BoM filename

KiBOM_CLI.py, README.md, bomlib/preferences.py
Hi @SchrodingersGat,
I wasn't quite happy with the implementation of the filename and the inclusion of variants (#58). This implementation is far more flexible (and extensible for further options in future). See what you think. I've kept the defaults such that they produce the same file names as the existing implementation.
Cheers.
------------------------------
Patch allows for user-specification of arbitrary filename. Will work on
both the command line and from within KiCAD. Should be extensible to
allow for other fields/options to be added in future. Currently only
supports version (%v), variant name/s (%V), and base file name (%O).
- Drop options for `include_version_number` and `include_variant_name`
- Add options for `output_file_name` and `variant_file_name_format`
Some examples …
=> Add support for arbitrary filenames

bomlib/preferences.py
Fix related to this discussion https://github.com/SchrodingersGat/KiBoM/issues/41#issuecomment-424698856
It accepts multiples white space (including the combination of tabs and spaces)
Sorry for the loooooong delay, I didn't see your answer before @SchrodingersGat
=> Flexible parser using whitespace instead of a single tab

README.md, bomlib/preferences.py
- Missed default bom.ini generation with pull #60
- Updated README.md to include an exact copy of the
default bom.ini generated (a lot of other people
seem to have also missed this step when adding
their features!).
-----
This solves #62, thanks for reporting @Brian245.
=> Fix default bom.ini generation

README.md
* Corrected snake_case preference names, `hide_headers` and `hide_pcb_info`, in example configuration file.
While I was there:
* Updated `usage` output.
* Added missing preference file options to documentation.
Pull Request created to resolve own issue: https://github.com/SchrodingersGat/KiBoM/issues/71
=> Fixed preference names in README (issue #71)

bomlib/component.py
Fixed issue https://github.com/SchrodingersGat/KiBoM/issues/73 by:
* Adding `from __future__ import unicode_literals` to turn every string literal into a unicode string by default. Could just have pre-fixed offending strings with `u`, but noticed the precedent has been set in other source files, and saves missing a string.
* Appended `.encode('utf-8')` to (potentially Unicode) strings before passing to `print`. Necessary because `sys.stdout.encoding` is set to `None`, which causes Python 2 (the one included in the KiCad package) to default to trying to encode as 'ascii', which fails. Alternatively, could have changed the default encoding (either by via `PYTHONIOENCODING` environment variable, or with the `sys.setdefaultencoding` hack) but was scared away by the many, many warnings, such …
=> Fix UnicodeEncodeError when printing Field Conflicts

bomlib/component.py
The KiCad 4.x description code had a fallback to the library description.
The new one didn't have it. This patch uses the fallback for both.
=> Description fallback fix for KiCad 5.x

bomlib/html_writer.py, bomlib/preferences.py
This is only for HTML output and generates a separated list containing the "do not fit" components.
=> Added 'html_generate_dnf' to add a separated section for DNF components

kibom/__main__.py, run-tests.sh, test/test_bom.py
Fixes https://github.com/SchrodingersGat/KiBoM/issues/98
=> Fixing output subdirectory issues

kibom/xml_writer.py
Line was commented out to fix an "unused variable" PEP warning. Putting the line back in.
=> Fix XML writer output

kibom/component.py
Now that prefs.pcbConfig is a list we can't do:
opt[1:].lower() == self.prefs.pcbConfig.lower()
I also figured out that there is no need to check for pcbConfig
Additionally this patch inverts the return value so the name of the
function makes sense (was inverted).
=> Fix DNC (isFixed)

kibom/units.py
The rest of the prefixes remain case insensitive.
So "1M" is 1 megaohm and "1m" is 1 milliohms.
But "1pf" is the same as "1PF".
=> Use "M" for "mega" and "m" for "milli"

kibom/__main__.py, kibom/units.py
The units parser currently prunes any comma.
But for many locales this is the decimal point separator.
This patch converts the current locale decimal point into a point.
=> Avoid destroying the current locale's decimal point

KiBOM_CLI.py, kibom/__main__.py, setup.py
This script was lost when kibom migrated from bomlib to kibom.
Having it isn't incompatible with kibom as a module.
=> Recover the KiBOM_CLI.py script.

kibom/html_writer.py, kibom/preferences.py
Digi-Key is one of the most complete electronic parts providers. Is often used as a reference.
If you have a field containing the Digi-Key part number you can make its column to contain links to the Digi-Key web page for this component.
Define the `digikey_link` option in the configuration file (i.e. `bom.ini`).
The value for this option is the column you want to convert into a link to the Digi-Key.
Note that this field must be a valid Digi-Key part number.
Example:
```
digikey_link = digikey#
```
This will make entries in the column `digikey#` (Digi-Key part number) links to the component's web page.
You can specify more than one fiel name using tab (ASCII 9) as separator:
```
digikey_link = digikey#	digikey_alt#
```
- Only available for HTML.
- Could break if Digi-Key changes it web …
=> Added 'digikey_link' to make a column with links to digikey P/Ns

README.md, kibom/component.py, kibom/netlist_reader.py, kibom/preferences.py
The alt_wrap option is not supported for all output formats, is error-prone, and poorly documented.
Removing as it is not super useful and is difficult to maintain.
=> Remove alt_wrap option

kibom/component.py, kibom/preferences.py
1 nF 50 V isn't the same as 1 nF 100 V and having separated columns for
each possible modifier is an overkill. Joining the fields to the value
is compact and natural.
Define a section named `[JOIN]`. In this section each entry is the name
of a field, followed by the name of the fields that will be added to
its column.
Use tab (ASCII 9) as separator. Example:
```
[JOIN]
Value	Voltage	Current	Power	Tolerance
```
This will attach the `voltage`, `current`, `power` and `tolerance` fields to the `value` field.
This patch replaces #81 and is smaller and more generic.
=> Added "join" to join fields like voltage, current, etc. with the value

kibom/units.py
I.e. "3.3 nF" is the same as "3.3nF"
Notes:
- The r" is needed to avoid flake8 warnings about escape sequences
- The ' inside " is just cosmetic
=> Add support for spaces between a value an its unit.

kibom/units.py
The regex used in units.py is huge, applied to all components many
times and compiled every time.
This patch uses a global variable to compile it once and reuse the
compiled regex.
=> Optimize the regex used to match component values

kibom/component.py, kibom/netlist_reader.py, kibom/units.py
It helps to get 5 pF before 1 nF
=> Modified the R/L/C sort to try to make sense of the multiplier

kibom/component.py
This was introduced by SchrodingersGat/KiBoM#117
Is just a call that still use the removed option.
Was detected by the CI pipeline.
=> Fixes extra parameter in getAltRefs

kibom/preferences.py
Added fallbacks to the current default values, avoiding an exception.
Should close issue #70
=> Tolerate no `output_file_name` and/or `variant_file_name_format`

kibom/component.py
I ran into this error myself, and could not find the culprit part because it didn't print the designator (it was just a plain `AttributeError`). This improvement helped hunt down the bad part on the schematic.
=> Improved error message when description can't be found (libpart None).

kibom/component.py, kibom/preferences.py
This patch fixes two Python 2.7 compatibility issues:
- The ConfigParser `fallback`, introduced in Python 3. Introduced by me on PR #121
- The use of f-strings in PR #127, they need Python 3.6 or newer
Note that for the first I introduced a helpful member checkStr, it was designed to be used in various places, but this is part of a bigger patch delayed by PR #112 an #120. The patch also fixes #123.
To get an idea the patch is INTI-CMNB/kibom#11
=> Fix Python 2 issues

kibom/columns.py, kibom/component.py, kibom/preferences.py
Hi there,
I've implemented adding a `sheetpath` column to the output BOM. currently, i just added it as a default column because it wasn't clear to me right away how to add it without it being default. Also, to avoid accidentally grouping components together with different sheetpaths, I had to it to the default `GROUP_FIELDS` section in the **bom.ini**.
Is this something that could be added to KiBoM? If so, could I get a review please? :)
ref #125
=> add support for sheetpath field in BOM

kibom/xml_writer.py
I noticed than non-ASCII characters (e.g. `±` when component tolerances) were getting destroyed when generating an `.xml` BOM. The fix was to specify the encoding when calling `toprettyxml()`, and then call `.decode('utf-8')` to get the bytes back into a Python string suitable to `output.write()`.
Oh and sorry about my previous pull-request that used `f-strings`, I didn't realize Python 2 was supported. I then noticed that KiCAD for Windows is still bundled with Python 2 :-).
=> Fixed utf-8 bug in the XML writer.

kibom/units.py
This patch include two things:
1) The addition to "MICRO SIGN U+00B5" as a valid micro prefix.
Fixes SchrodingersGat/KiBoM#133
2) A fix to the Ohms sign. As we are using a lower case compare
we must compare to lowercase omega, not uppercase omega.
Fixes SchrodingersGat/KiBoM#134
BTW: I added a few comments to clarify the code.
=> Fixes to micro and ohm characters.

setup.py
pip should now automatically add `kibom` to the user's path, so cloning the repo and providing a full path to KiBoM is no longer necessary.
Also the entry_points method seems to have [better cross platform compatibility](https://stackoverflow.com/questions/18787036/difference-between-entry-points-console-scripts-and-scripts-in-setup-py) than the `scripts` method.
=> add kibom.__main__:main entry point

README.md, kibom/component.py, kibom/preferences.py
When reference designators are grouped on a single line in the output file, they are separated by a hard-coded space character. Some PCB assembly services want different characters (primarily ",") to separate the reference designators. This pull request creates a configuration file option "ref_separator" that defaults to the original hard-coded space but can be changed to a comma or anything else needed by adding a line to the configuration file.
modified:   ../README.md
modified:   component.py
modified:   preferences.py
=> Reference Designator Separators

kibom/preferences.py
A small detail. 
If we don't quote it the generated file will be read as `ref_separator = ''`
=> Fixed the ref_separator save, must be quoted.

kibom/component.py
the misplaced parenthesis causes the code to raise an `IndexError` when it's trying to format the error message when raising the `AttributeError`
=> Fix misplaced parenthesis for raise AttributeError

README.md, kibom/__main__.py, kibom/component.py, kibom/preferences.py
Current KiBOM code supports loading/unloading a part depending on the exported variant.
However, it does not support changing the value of `Value` field to support different component values in different variants.
This is a straight forward implementation to handle this, so no hurt feeling if you see potential flaws :smile: 
Happy to resolve feedback as necessary.
=> Add support for variants of the Value field

kibom/bom_writer.py, kibom/component.py, kibom/csv_writer.py, kibom/html_writer.py, kibom/preferences.py, kibom/xlsx_writer.py, kibom/xml_writer.py
Column names displayed in the table head are the names of the KiCad fields or the internal names used by KiBoM.
Sometimes the names aren't pretty. As an example is common to use `manf#` for the part name used by the component manufacturer.
Using long names for KiCad fields is a bad idea.
This patch allows to rename the columns names so you can use pretty names in the headings.
You must define a `COLUMN_RENAME` section in the configuration file.
Then add entries with the name of the original field and the name you want, separated by a tab (ASCII 9).
Here is an example:
```
[COLUMN_RENAME]
manf#	Manufacturer part number
```
Note that you must use a tab as separator. Using a space won't work because *Manufacturer part number* also has spaces.
The separator must be a tab.
- This patch also …
=> Add a mechanism to rename columns

kibom/html_writer.py, kibom/preferences.py
Replaces #79
Having a separated column for the datasheet is an overkill. We can make
that another column contains this information as a link. The part
number is a suitable column.
This patch allows configuring it.
Define the datasheet_as_link option in the configuration file (i.e.
bom.ini).
The value for this option is the column you want to convert into a link
to the datasheet. Example:
```
datasheet_as_link = manf#
```
This will make entries in the column manf# (manufacturer part number)
links to the datasheet.
Only available for HTML
=> Adds an option to make a column to contain datasheet links

kibom/component.py
When getting the description of a component, if "description" does not exist, look for "Description" instead. I noticed that when using KiCAD 7, my generated BOM was missing a lot of information. I'm not sure if the right thing to do is simply to make this case-insensitive, or simply to check a few different options. In my project, I have several parts libraries from various sources (Ultra Librarian, SnapEDA, Component Search Engine), and the fields associated with the parts vary quite a bit; this change worked well for my use case.
This builds off of #177, and seems to resolve issue #178.
=> Try different capitalization for Description field

kibom/component.py
When using variants the Config fields may be quite different between
components.
Reporting conflicts in Config generates noise.
=> Do not report warnings about conflicts in `Config` field

kibom/component.py
This is just a "backport" of the INTI-CMNB/KiBoM#23 PR by @PatrickBaus 
Replacing field values using the complex_variant = True option is not case sensitive.
If the field name to be replaced contains uppercase letters, the comparison will fail because of the following code
```python
if field.get('field', 'name') == name:
```
The first part of the comparison may contain uppercase letters. The latter part is typically lower case, but for safety reasons, I apply lower() as well. This PR contains the fix and also squashes some trailing white spaces.
=> Fixed changing field values via the complex_variant option

README.md, kibom/__main__.py, kibom/preferences.py
Allows things like KiCost:Field used as field name.
This is important to interact with KiCost because it supports things like *KiCost:Distributor:pricing* to specify the *pricing* for a local *Distributor*.
The .INI file will parse the `:` as a key/value delimiter and you'll get *KiCost*, instead of the full name, for places like **IGNORE_COLUMNS**. 
See INTI-CMNB/KiBoM#20
=> Added a command line option to exclude `:` as INI delimiter
